prjdemo:
  outputs:
    dev:
      account: fqb16614
      database: analytics
      password: Sachin@10
      role: analyticsengineer
      schema: dbt_murali
      threads: 3
      type: snowflake
      user: sachin
      warehouse: transform_wh
  target: dev
