name: Deploy_dbt
on:
 schedule:
    - cron: 0/5 * * * *
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@masterbranch
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip3 install dbt-snowflake
          dbt deps
      - name: Run dbt
        run: |
          dbt run
      - name: Test using dbt 
          dbt test
